image: python:3.10-bullseye

variables:
  PYTHON_TAG: py3
  ABI_TAG: none
  PLATFORM_TAG: any
  PACKAGE_EXTENSION: whl
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build:
  stage: build
  script:
    # Remove explicit version from setup.py, its on the 6th line
    - sed '6d' setup.py -i
    # Show setup.py
    - cat setup.py    
    # Get version. Variable CI_COMMIT_TAG is set only when tag was pushed.
    - export VERSION=$(if [[ "$CI_COMMIT_TAG" == "" ]]; then echo 0.0.0; else echo $CI_COMMIT_TAG | cut -c 2-; fi)
    - python3 setup.py setopt --command=metadata --option=version --set-value=$VERSION
    - echo VERSION=$VERSION
    # Get package filename
    - export WHEEL_NAME=$(python3 setup.py --name | tr '-' '_')
    - export PACKAGE=$WHEEL_NAME-$VERSION-$PYTHON_TAG-$ABI_TAG-$PLATFORM_TAG.$PACKAGE_EXTENSION
    - echo PACKAGE=$PACKAGE
    - python3 setup.py bdist_wheel
    - echo $PACKAGE > dist/.package-name
    - ls
  only:
    - branches
    - tags
  artifacts:
    paths:
      - mkdocs_swagger_ui_plugin/dist
    expire_in: 1 day
    
deploy:
  image: curlimages/curl:latest
  stage: deploy
  script:
    - export PACKAGE=$(cat mkdocs_swagger_ui_plugin/dist/.package-name)
    - 'curl -u $PYPI_USER:$PYPI_PASSWORD -X POST "$PYPI_UPLOAD_URL" -H  "Content-Type: multipart/form-data" -F "pypi.asset=@mkdocs_swagger_ui_plugin/dist/$PACKAGE"'
  dependencies:
    - build
  only:
    - tags

